### ISSUE TITLE
Optimize phase_randomize() function. It's really slow.

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/podcast-encoding#18]
https://github.com/hvgazula/podcast-encoding/blob/main/podenc_phase_shuffle.py#L32

**Comment by hvgazula** [comment]
Here are the bottleneck lines 
https://github.com/hvgazula/podcast-encoding/blob/main/podenc_phase_shuffle.py#L55-L56

replace with
```
import numexpr as ne
fft_data[:, :, pos_freq] = ne.evaluate('fft_data[:, :, pos_freq] * exp(1j * phase_shifts')
fft_data[:, :, neg_freq] = ne.evaluate('fft_data[:, :, neg_freq] * exp(-1j * phase_shifts') 
```

`numexpr` seems to be faster than `numba` (surprisingly) however the conda environment issue prevent `numexpr` installation

**Comment by hvgazula** [comment]
@zkokaja  👆 . You may be interested.

**Comment by zkokaja** [comment]
What conda environment issue? Is it something we can solve?

**Comment by hvgazula** [comment]
Some conflicts. Yes, we can solve it by stopping using scotty altogether ;). Personally, the environment creation hasn't always been smooth for me on scotty. I tagged you so you'd know about `numexpr` unless you already knew it.

**Comment by hvgazula** [comment]
resolved
